---
# Default Variables for CIS Ubuntu Linux 20.04 LTS Benchmark v1.0.0 Section 2

# Variables for 2.1.1
ubuntu_2004_cis_section2_rule_2_1_1: true

ubuntu_2004_cis_section2_rule_2_1_1_params_package_name: xinetd
ubuntu_2004_cis_section2_rule_2_1_1_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_1_1_params_package_purge: yes

# Variables for 2.1.2
ubuntu_2004_cis_section2_rule_2_1_2: true

ubuntu_2004_cis_section2_rule_2_1_2_params_package_name: openbsd-inetd
ubuntu_2004_cis_section2_rule_2_1_2_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_1_2_params_package_purge: yes

# Variables for 2.2.1.1, 2.2.1.2, 2.2.1.3 and 2.2.1.4
ubuntu_2004_cis_section2_rule_2_2_1_1: true
ubuntu_2004_cis_section2_rule_2_2_1_2: true
ubuntu_2004_cis_section2_rule_2_2_1_3: true
ubuntu_2004_cis_section2_rule_2_2_1_4: true

ubuntu_2004_cis_time_synchronization_package_state: present

ubuntu_2004_cis_section2_rule_2_2_1_1_params_timesyncd_service_name: systemd-timesyncd
ubuntu_2004_cis_section2_rule_2_2_1_1_params_timesyncd_service_enabled_state: yes
ubuntu_2004_cis_section2_rule_2_2_1_1_params_timesyncd_service_masked_true: yes
ubuntu_2004_cis_section2_rule_2_2_1_1_params_chrony_package: chrony
ubuntu_2004_cis_section2_rule_2_2_1_1_params_chrony_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_1_1_params_chrony_package_purge: yes
ubuntu_2004_cis_section2_rule_2_2_1_1_params_ntp_package: ntp
ubuntu_2004_cis_section2_rule_2_2_1_1_params_ntp_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_1_1_params_ntp_package_purge: yes

ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_name: systemd-timesyncd
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_enabled_state: yes
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_masked_true: no
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_state: restarted
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_path: /etc/systemd/timesyncd.conf
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_section: Time
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_ntp_option: NTP
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_ntp_value: 0.debian.pool.ntp.org 1.debian.pool.ntp.org
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_fallbackntp_option: FallbackNTP
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_fallbackntp_value: 2.debian.pool.ntp.org 3.debian.pool.ntp.org
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_rootdistancemaxsec_option: RootDistanceMaxSec
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_rootdistancemaxsec_value: '1'
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_owner: root
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_group: root
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_mode: 0644
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_state: present
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_service_conffile_no_extra_spaces: yes
ubuntu_2004_cis_section2_rule_2_2_1_2_params_timesyncd_setntptrue_command: timedatectl set-ntp true

ubuntu_2004_cis_section2_rule_2_2_1_3_params_chrony_template_src: section_02/2.2.1.3_chrony.conf.j2
ubuntu_2004_cis_section2_rule_2_2_1_3_params_chrony_template_dest: /etc/chrony/chrony.conf
ubuntu_2004_cis_section2_rule_2_2_1_3_params_chrony_template_owner: root
ubuntu_2004_cis_section2_rule_2_2_1_3_params_chrony_template_group: root
ubuntu_2004_cis_section2_rule_2_2_1_3_params_chrony_template_mode: '0644'

ubuntu_2004_cis_section2_rule_2_2_1_4_params_ntp_template_src: section_02/2.2.1.4_ntp.conf.j2
ubuntu_2004_cis_section2_rule_2_2_1_4_params_ntp_template_dest: /etc/ntp.conf
ubuntu_2004_cis_section2_rule_2_2_1_4_params_ntp_template_owner: root
ubuntu_2004_cis_section2_rule_2_2_1_4_params_ntp_template_group: root
ubuntu_2004_cis_section2_rule_2_2_1_4_params_ntp_template_mode: '0644'

# Variables for 2.2.2
ubuntu_2004_cis_section2_rule_2_2_2: true

ubuntu_2004_cis_section2_rule_2_2_2_params_package_name: xserver-xorg*
ubuntu_2004_cis_section2_rule_2_2_2_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_2_params_package_purge: yes

# Variables for 2.2.3
ubuntu_2004_cis_section2_rule_2_2_3: true

ubuntu_2004_cis_section2_rule_2_2_3_params_package_name: avahi-daemon
ubuntu_2004_cis_section2_rule_2_2_3_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_3_params_package_purge: yes

# Variables for 2.2.4
ubuntu_2004_cis_section2_rule_2_2_4: true

ubuntu_2004_cis_section2_rule_2_2_4_params_package_name: cups
ubuntu_2004_cis_section2_rule_2_2_4_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_4_params_package_purge: yes

# Variables for 2.2.5
ubuntu_2004_cis_section2_rule_2_2_5: true

ubuntu_2004_cis_section2_rule_2_2_5_params_package_name: isc-dhcp-server
ubuntu_2004_cis_section2_rule_2_2_5_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_5_params_package_purge: yes

# Variables for 2.2.6
ubuntu_2004_cis_section2_rule_2_2_6: true

ubuntu_2004_cis_section2_rule_2_2_6_params_package_name: slapd
ubuntu_2004_cis_section2_rule_2_2_6_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_6_params_package_purge: yes

# Variables for 2.2.7
ubuntu_2004_cis_section2_rule_2_2_7: true

ubuntu_2004_cis_section2_rule_2_2_7_params_package_name:
  - nfs-kernel-server
  - rpcbind
ubuntu_2004_cis_section2_rule_2_2_7_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_7_params_package_purge: yes

# Variables for 2.2.8
ubuntu_2004_cis_section2_rule_2_2_8: true

ubuntu_2004_cis_section2_rule_2_2_8_params_package_name: bind9
ubuntu_2004_cis_section2_rule_2_2_8_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_8_params_package_purge: yes

# Variables for 2.2.9
ubuntu_2004_cis_section2_rule_2_2_9: true

ubuntu_2004_cis_section2_rule_2_2_9_params_package_name: vsftpd
ubuntu_2004_cis_section2_rule_2_2_9_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_9_params_package_purge: yes

# Variables for 2.2.10
ubuntu_2004_cis_section2_rule_2_2_10: true

ubuntu_2004_cis_section2_rule_2_2_10_params_package_name: apache2
ubuntu_2004_cis_section2_rule_2_2_10_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_10_params_package_purge: yes

# Variables for 2.2.11
ubuntu_2004_cis_section2_rule_2_2_11: true

ubuntu_2004_cis_section2_rule_2_2_11_params_package_name:
  - dovecot-imapd
  - dovecot-pop3d
ubuntu_2004_cis_section2_rule_2_2_11_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_11_params_package_purge: yes

# Variables for 2.2.12
ubuntu_2004_cis_section2_rule_2_2_12: true

ubuntu_2004_cis_section2_rule_2_2_12_params_package_name: samba
ubuntu_2004_cis_section2_rule_2_2_12_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_12_params_package_purge: yes

# Variables for 2.2.13
ubuntu_2004_cis_section2_rule_2_2_13: true

ubuntu_2004_cis_section2_rule_2_2_13_params_package_name: squid
ubuntu_2004_cis_section2_rule_2_2_13_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_13_params_package_purge: yes

# Variables for 2.2.14
ubuntu_2004_cis_section2_rule_2_2_14: true

ubuntu_2004_cis_section2_rule_2_2_14_params_package_name: snmpd
ubuntu_2004_cis_section2_rule_2_2_14_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_14_params_package_purge: yes

# Variables for 2.2.15
ubuntu_2004_cis_section2_rule_2_2_15: true

ubuntu_2004_cis_section2_rule_2_2_15_params_path: /etc/postfix/main.cf
ubuntu_2004_cis_section2_rule_2_2_15_params_line: inet_interfaces = localhost
ubuntu_2004_cis_section2_rule_2_2_15_params_regexp: ^inet_interfaces.*
ubuntu_2004_cis_section2_rule_2_2_15_params_state: present
ubuntu_2004_cis_section2_rule_2_2_15_params_owner: root
ubuntu_2004_cis_section2_rule_2_2_15_params_group: root
ubuntu_2004_cis_section2_rule_2_2_15_params_mode: '0644'

# Variables for 2.2.16
ubuntu_2004_cis_section2_rule_2_2_16: true

ubuntu_2004_cis_section2_rule_2_2_16_params_package_name: rsync
ubuntu_2004_cis_section2_rule_2_2_16_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_16_params_package_purge: yes

# Variables for 2.2.17
ubuntu_2004_cis_section2_rule_2_2_17: true

ubuntu_2004_cis_section2_rule_2_2_17_params_package_name: nis
ubuntu_2004_cis_section2_rule_2_2_17_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_2_17_params_package_purge: yes

# Variables for 2.3.1
ubuntu_2004_cis_section2_rule_2_3_1: true

ubuntu_2004_cis_section2_rule_2_3_1_params_package_name: nis
ubuntu_2004_cis_section2_rule_2_3_1_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_3_1_params_package_purge: yes

# Variables for 2.3.2
ubuntu_2004_cis_section2_rule_2_3_2: true

ubuntu_2004_cis_section2_rule_2_3_2_params_package_name: rsh-client
ubuntu_2004_cis_section2_rule_2_3_2_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_3_2_params_package_purge: yes

# Variables for 2.3.3
ubuntu_2004_cis_section2_rule_2_3_3: true

ubuntu_2004_cis_section2_rule_2_3_3_params_package_name: talk
ubuntu_2004_cis_section2_rule_2_3_3_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_3_3_params_package_purge: yes

# Variables for 2.3.4
ubuntu_2004_cis_section2_rule_2_3_4: true

ubuntu_2004_cis_section2_rule_2_3_4_params_package_name: telnet
ubuntu_2004_cis_section2_rule_2_3_4_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_3_4_params_package_purge: yes

# Variables for 2.3.5
ubuntu_2004_cis_section2_rule_2_3_5: true

ubuntu_2004_cis_section2_rule_2_3_5_params_package_name: ldap-utils
ubuntu_2004_cis_section2_rule_2_3_5_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_3_5_params_package_purge: yes

# Variables for 2.3.6
ubuntu_2004_cis_section2_rule_2_3_6: true

ubuntu_2004_cis_section2_rule_2_3_6_params_package_name: rpcbind
ubuntu_2004_cis_section2_rule_2_3_6_params_package_state: absent
ubuntu_2004_cis_section2_rule_2_3_6_params_package_purge: yes

# Variables for 2.4
ubuntu_2004_cis_section2_rule_2_4: true

ubuntu_2004_cis_section2_rule_2_4_params_script: 2.4.listening_services.sh
