---
- name: Ensure required kernel modules are loaded
  modprobe: name={{ item }} state=present
  loop:
    - br_netfilter
    - ip6_udp_tunnel
    - ip_set
    - ip_set_hash_ip
    - ip_set_hash_net
    - iptable_filter
    - iptable_nat
    - iptable_mangle
    - iptable_raw
    - nf_conntrack_netlink
    - nf_conntrack
    - nf_defrag_ipv4
    - nf_nat
    - nfnetlink
    - udp_tunnel
    - veth
    - vxlan
    - x_tables
    - xt_addrtype
    - xt_conntrack
    - xt_comment
    - xt_mark
    - xt_multiport
    - xt_nat
    - xt_recent
    - xt_set
    - xt_statistic
    - xt_tcpudp
    - ip_tables
    - ipt_REJECT
    - ipt_rpfilter
    - ipt_set
    - nf_conntrack_netlink
    - conntrack_proto_sctp
    - sctp
    - xt_addrtype
    - xt_comment
    - xt_conntrack
    - xt_icmp
    - xt_ipvs
    - xt_multiport
    - xt_rpfilter
    - xt_sctp
    - xt_set
    - xt_u32
    - ipip

- name: Add required kernel modules to automatically loaded modules
  blockinfile:
    path: /etc/modules-load.d/modules.conf
    backup: true
    create: true
    block: |
      br_netfilter
      ip6_udp_tunnel
      ip_set
      ip_set_hash_ip
      ip_set_hash_net
      iptable_filter
      iptable_nat
      iptable_mangle
      iptable_raw
      nf_conntrack_netlink
      nf_conntrack
      nf_defrag_ipv4
      nf_nat
      nf_nat_masquerade_ipv4
      nfnetlink
      udp_tunnel
      veth
      vxlan
      x_tables
      xt_addrtype
      xt_conntrack
      xt_comment
      xt_mark
      xt_multiport
      xt_nat
      xt_recent
      xt_set
      xt_statistic
      xt_tcpudp
      ip_tables
      ipt_REJECT
      ipt_rpfilter
      ipt_set
      nf_conntrack_netlink
      conntrack_proto_sctp
      sctp
      xt_addrtype
      xt_comment
      xt_conntrack
      xt_icmp
      xt_ipvs
      xt_multiport
      xt_rpfilter
      xt_sctp
      xt_set
      xt_u32
      ipip
      
